[server]
host = "localhost"
port = 8080
allowOrigins = ["*"]
allowMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

[database]
host = "localhost"
port = 3306
username = "root"
password = "0I38xO4KFVKnhmWt-ycnaBg2QupMv1zlRmLZXhvjxZ2K-g=="