[server]
host = "localhost"
port = 8080
allowOrigins = ["*"]
allowMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

[database]
host = "localhost"
port = 3306
database = "fund_manager"
username = "fundManagerApp"
password = "LTCBll6rg8WNr4YDL25kz8JNebKwVUh7yTTG5zGTbDeW13xpZ2eiWUreQg=="